---
- name: Make sure the CA certificates are available
  apt:
    pkg: ca-certificates
    state: present

- name: Add PostgreSQL repository apt-key
  apt_key:
    id: "{{ postgresql_apt_key_id }}"
    url: "{{ postgresql_apt_key_url }}"
    state: present

- name: Add PostgreSQL repository
  apt_repository:
    repo: "{{ postgresql_apt_repository }}"
    state: present

- name: Install PostgreSQL
  apt:
    name:
      - "postgresql-{{postgresql_version}}"
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"

- name: Start PostgreSQL server
  systemd:
    name: "{{ postgresql_service_name }}"
    enabled: yes
    state: started

- name: Wait for server to start
  wait_for:
    port: 5432