---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/empty.yml"
  tags: [always]

- import_tasks: install_apt.yml
  tags: [common, postgresql-install]

- import_tasks: config.yml
  tags: [common, postgresql-config]

- import_tasks: config_slave.yml
  tags: [pgslave, postgresql-slave-config]
